import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {registrySummary,registry} from '../src/core/composition-registry.mjs';import {compose} from '../src/core/compose.mjs';import {generateWebsite,generatedProjectDir} from '../src/core/generator.mjs';

test('Composition Registry baseline remains backward-compatible under R2',()=>{const s=registrySummary();assert.ok(s.counts.sectionTemplates>=200);assert.ok(s.counts.primitives>=50);assert.ok(s.counts.pageBlueprints>=30);assert.ok(s.counts.artDirections>=15);assert.ok(s.counts.mediaRoles>=30);assert.ok(s.counts.interactions>=40);assert.ok(s.counts.connectors>=20);assert.ok(s.counts.plugins>=20);assert.ok(s.counts.pluginSets>=10);assert.ok(s.counts.workflows>=10);assert.ok(s.counts.patterns>=60)});

test('premium techno club resolves nightclub blueprint, cinematic composition and plugin set',()=>{const p=compose('Premium techno club in Prague with tickets, DJs, gallery, events, cinematic dark design and mobile first.');assert.equal(p.siteBlueprint.id,'venue-nightclub');assert.ok(p.siteBlueprint.pageCount>=8);assert.ok(['dark-cinematic','neo-industrial','high-energy'].includes(p.visual.artDirection.theme.id));assert.ok(p.visual.templates.catalogCount>=200);assert.ok(p.visual.plugins.selected.length>=3);assert.ok(p.visual.workflow.primary.id.includes('venue'));assert.ok(p.visual.interactions.selected.some(x=>x.id==='sticky-cta'));});

test('section resolver exposes approved scored templates with renderer compatibility',()=>{const p=compose('Premium techno club with tickets, gallery and cinematic experience.');for(const s of p.visual.sections){assert.ok(s.template.includes('.r1'));assert.ok(s.rendererKey);assert.ok(s.qualityScore>=84);assert.ok(s.selectionScore>=s.qualityScore);assert.ok(s.availableCount>=1)}});

test('plugin install authority remains explicit and connector resolution is fail-closed',()=>{const p=compose('SaaS dashboard with login, product analytics and subscription checkout.');assert.equal(p.visual.plugins.installAuthority,'EXPLICIT_APPROVAL_REQUIRED');assert.ok(p.visual.plugins.selected.every(x=>x.trustScore>=85));assert.ok(p.visual.connectors.selected.every(x=>x.failClosed===true));});

test('generator emits blueprint pages and registry receipts',()=>{const out=generateWebsite('Premium techno club in Prague with tickets, DJs, gallery, events and dark cinematic design.');const dir=generatedProjectDir(out.projectId);assert.ok(fs.existsSync(`${dir}/site-blueprint.json`));assert.ok(fs.existsSync(`${dir}/composition-registry-selection.json`));assert.ok(fs.existsSync(`${dir}/events/index.html`));assert.ok(fs.existsSync(`${dir}/artists/index.html`));assert.ok(fs.existsSync(`${dir}/gallery/index.html`));assert.ok(fs.existsSync(`${dir}/runtime/src/pages/events/index.astro`));assert.ok(out.receipt.checks.some(x=>x.id==='composition-registry'&&x.status==='PASS'));fs.rmSync(dir,{recursive:true,force:true});});

test('all template registry entries have quality and trust metadata',()=>{const xs=registry('sectionTemplates');assert.ok(xs.length>=200);assert.ok(xs.every(x=>Number.isFinite(x.qualityScore)&&x.trust==='approved'&&x.maturity));});
