import { localizeContentModel } from './locale-contract.mjs';
const pad=n=>String(n).padStart(2,'0');
const words=(xs,i)=>xs[i%xs.length];

function venue(plan){
  const brand=plan.brand.identity.name;
  const loc=plan.brand.content.location||'Prague';
  const eventNames=['Dark Matter','Frequency','Hypnotic','Eclipse'];
  const artists=['ANNA','FJAAK','Recondite','VTSS'];
  return {
    hero:{eyebrow:`${loc.toUpperCase()} AFTER DARK`,headline:'Immersive techno nights.',subheadline:`Raw sound. Curated energy. A premium club experience in the heart of ${loc}.`,primary:'See next event',secondary:'Buy tickets'},
    navigation:['Experience','Events','Artists','Gallery','Tickets','Contact'],
    'next-event':{kicker:'NEXT EVENT',title:eventNames[0],date:'SAT 31 MAY',time:'23:00 — 06:00',location:`${brand}, ${loc}`,lineup:artists.slice(0,3),cta:'View event & tickets'},
    artists:{kicker:'FEATURED ARTISTS',items:artists.map((name,i)=>({name,meta:i===2?'LIVE':'DJ SET',mediaLabel:`Artist ${pad(i+1)}`}))},
    gallery:{kicker:'FROM THE CLUB',title:'Inside the room.',items:Array.from({length:6},(_,i)=>({title:words(['Main room','Light architecture','Crowd energy','Booth perspective','Late set','After image'],i),mediaLabel:`Club ${pad(i+1)}`}))},
    schedule:{kicker:'NIGHT FLOW',title:'One night, one continuous arc.',steps:['Doors & warm-up','Peak room','Closing sequence']},
    experience:{kicker:'THE EXPERIENCE',title:'Sound, design and atmosphere engineered for connection.',body:'A night designed as one continuous system: room, light, sound, service and crowd.',features:[['IMMERSIVE SOUND','High-fidelity system tuned for depth and clarity.'],['LIGHT & VISUALS','A responsive light environment that shapes the night.'],['SAFE & INCLUSIVE','Respectful space and clear house standards.'],['PREMIUM BAR','Fast service, considered drinks, no unnecessary friction.']]},
    'latest-content':{kicker:'UPCOMING EVENTS',items:eventNames.slice(1).map((title,i)=>({title,date:`${[14,28,12][i]} ${['JUN','JUN','JUL'][i]}`,time:'23:00 — 06:00',meta:'CLUB NIGHT'}))},
    proof:{kicker:'WHY THE ROOM WORKS',metrics:[['01','Purpose-built sound'],['02','Curated lineups'],['03','Clear night flow']]},
    faq:{kicker:'GOOD TO KNOW',items:[['Doors & entry','Tickets and entry details stay visible before arrival.'],['Accessibility','Key access information belongs on the event page, not behind a message.'],['House policy','Respect, consent and safety are explicit parts of the experience.']]},
    location:{kicker:'LOCATION',title:`In the heart of ${loc}.`,body:'Directions, opening information and transport belong one tap away from the ticket flow.'},
    final:{eyebrow:'BE PART OF THE NIGHT',headline:'Choose the night.',primary:'Buy tickets',secondary:'Membership'},
    footer:{location:`${loc}, Czech Republic`,newsletter:'Be first to know about events and special releases.'}
  };
}

function local(plan){return {hero:{eyebrow:'LOCAL / TRUSTED',headline:'A better next step starts here.',subheadline:'Clear services, real proof and a direct path to booking.',primary:'Book a visit',secondary:'See results'},navigation:['Services','Results','Process','FAQ','Contact'],services:{kicker:'SERVICES',items:['Consultation','Primary service','Follow-up','Specialist option'].map((title,i)=>({title,body:['Start with the right diagnosis.','A clear, outcome-led core service.','Know exactly what happens after delivery.','A focused option for the complex cases.'][i]}))},proof:{kicker:'PROOF',metrics:[['01','Verified work'],['02','Clear process'],['03','Local trust']]},process:{kicker:'PROCESS',steps:['Tell us what you need','Choose the right path','Confirm the next step']},gallery:{kicker:'REAL WORK',title:'Proof should be visible.',items:Array.from({length:5},(_,i)=>({title:`Outcome ${pad(i+1)}`,mediaLabel:`Work ${pad(i+1)}`}))},faq:{kicker:'FAQ',items:[['What happens first?','A short assessment before commitment.'],['How long does it take?','Scope and timing are stated before booking.'],['What should I prepare?','Only the information needed for the first step.']]},location:{kicker:'FIND US',title:plan.brand.content.location||'Local and easy to reach.',body:'Address, hours and directions should support conversion, not interrupt it.'},final:{eyebrow:'READY',headline:'Make the next move.',primary:'Book a visit',secondary:'Contact us'},footer:{location:plan.brand.content.location||'Local service',newsletter:'Useful updates, not inbox noise.'}}}

function product(plan){const saas=plan.project.archetype==='saas';return {hero:{eyebrow:saas?'PRODUCT / VALUE':'TASK / FOCUS',headline:saas?'See the value before the demo ends.':'Put the core task first.',subheadline:'A focused product story built around real workflows, proof and the next action.',primary:'Start with the product',secondary:'See workflow'},navigation:['Product','Workflow','Integrations','Pricing','Security'], 'product-proof':{kicker:'PRODUCT',title:'Make the product visible.',body:'Show the primary workflow before asking people to decode a feature list.'},'task-preview':{kicker:'CORE TASK',title:'The work surface, not a decorative dashboard.',body:'A clear stage for the task users return to every day.'},'feature-grid':{kicker:'CAPABILITIES',items:['Automate','Coordinate','Measure','Control'].map((title,i)=>({title,body:['Remove repetitive steps.','Keep work and ownership legible.','Turn activity into useful evidence.','Keep authority explicit.'][i]}))},workflow:{kicker:'WORKFLOW',steps:['Connect context','Resolve the next action','Verify the outcome']},integrations:{kicker:'INTEGRATIONS',items:['API','Data','Identity','Analytics'].map(title=>({title,body:'Connect only when the capability requires it.'}))},security:{kicker:'SECURITY',metrics:[['01','Explicit authority'],['02','Evidence'],['03','Fail closed']]},pricing:{kicker:'PRICING',items:['Start','Grow','Scale'].map((title,i)=>({title,price:['Free','€49','Custom'][i],body:'A clear boundary between plan and outcome.'}))},proof:{kicker:'PROOF',metrics:[['01','Less friction'],['02','More clarity'],['03','Traceable outcomes']]},faq:{kicker:'FAQ',items:[['Can it fit the current stack?','Integrations are capability-driven, not mandatory.'],['What changes first?','The primary workflow, then the surrounding system.'],['How is risk handled?','Every production action can be gated and evidenced.']]},final:{eyebrow:'NEXT STEP',headline:'Start with the real workflow.',primary:'Start now',secondary:'Talk to us'},footer:{location:'Available globally',newsletter:'Product updates and practical releases.'}}}

function productApplicationMode(plan){
  const text=String(plan.project.brief||'').toLowerCase(), domain=plan.project.domainArchetype;
  if(domain==='finance'||/(fintech|banking|digital bank|payments?|wallet|account balance|transactions?)/i.test(text)) return 'financial';
  if(/(monitoring|observability|alerts?|incidents?|uptime|latency|api health|status page)/i.test(text)) return 'observability';
  if(/(logistics|shipments?|fleet|warehouse|dispatch|exceptions?|operations dashboard|supply chain)/i.test(text)) return 'operations';
  if(/(developer|sdk|api platform|documentation|docs|endpoint|webhook)/i.test(text)) return 'developer';
  return 'workspace';
}

function productApplication(plan){
  const mode=productApplicationMode(plan), docs=(plan.product?.capabilityIds||[]).includes('content.documentation');
  const modes={
    observability:{
      hero:['MONITOR / RESPOND','See API health before users feel the failure.','Live checks, alerts, incident context and integrations arranged around detection and response.','Inspect monitoring','See alert flow'],
      navigation:['Overview','Monitors','Alerts','Incidents','Integrations','Docs'],
      product:['LIVE SIGNAL','Health, latency and failures in one operational view.','Keep the current state, recent change and affected surface visible together.',['Endpoint health','Latency & errors','Recent change']],
      task:['INVESTIGATE','Move from signal to cause without losing context.','The primary work surface should support triage, ownership and recovery.',['Current status','Failure context','Owner / next action']],
      steps:['Detect a meaningful change','Inspect affected endpoints and context','Route the alert to an owner','Verify recovery'],
      integrations:[['API / checks','Connect the monitored surface.'],['Alerting','Route only actionable signals.'],['Incident flow','Keep ownership and response context attached.'],['Data','Retain the evidence needed to verify recovery.']],
      proof:[['01','Health visible'],['02','Alert context'],['03','Recovery trace']],
      final:['NEXT INCIDENT','Start with the signal that needs attention.','Inspect monitoring','View integrations']
    },
    operations:{
      hero:['OPERATE / EXCEPTIONS','See shipments, exceptions and next actions in one live operating view.','Status, ownership and operational context stay together so teams can resolve the next exception without hunting across systems.','Open operations view','See exception flow'],
      navigation:['Operations','Shipments','Exceptions','Analytics','Team','Security'],
      product:['OPERATING MAP','Turn movement into a shared operational picture.','Surface current shipment state, exceptions and ownership before secondary reporting.',['Shipment state','Exception queue','Operational ownership']],
      task:['RESOLVE','Work the exception from signal to resolution.','The core task is deciding what needs attention, who owns it and whether the outcome is resolved.',['Priority exception','Assigned owner','Resolution state']],
      steps:['Watch the current operating state','Triage the exception','Assign the next action','Confirm resolution'],
      integrations:[['Carrier feeds','Bring shipment status into one operational context.'],['Orders','Link movement to the underlying work.'],['Identity','Make ownership explicit.'],['Analytics','Measure patterns after the operational task is clear.']],
      proof:[['01','Live status'],['02','Owned exceptions'],['03','Resolution history']],
      final:['NEXT SHIFT','Start with the real operating queue.','Open operations view','Review integrations']
    },
    financial:{
      hero:['ACCOUNT / CONTROL','See account state, movement and controls before taking action.','Balances, transactions, security context and the next permitted action belong in one trustworthy financial workspace.','Open account view','Review controls'],
      navigation:['Accounts','Activity','Payments','Controls','Security','Help'],
      product:['ACCOUNT STATE','Make current financial state legible before the action.','Show balances, movement and relevant controls without inventing rates, returns or account data.',['Account overview','Recent activity','Control state']],
      task:['TRANSACT','Keep the action, verification and resulting state connected.','The work surface should show what is changing, what must be verified and what happened next.',['Action details','Verification','Resulting state']],
      steps:['Review current state','Choose the permitted action','Verify the request','Confirm the resulting state'],
      integrations:[['Accounts','Use verified provider data.'],['Payments','Bind only approved payment rails.'],['Identity','Keep authentication and authority explicit.'],['Documents','Attach source-backed records and disclosures.']],
      proof:[['01','State visible'],['02','Authority explicit'],['03','Audit trail']],
      final:['NEXT ACTION','Continue only with verified account context.','Open account view','Review security']
    },
    developer:{
      hero:['BUILD / INTEGRATE','Get from first request to a working integration without hunting for context.','API surface, examples, documentation and integration state arranged around the developer journey.','Explore the API','Read the docs'],
      navigation:['API','Docs','Examples','Integrations','Status','Security'],
      product:['API SURFACE','Put the usable interface before the marketing inventory.','Show the primary resources, request shape and integration boundaries early.',['Core resources','Request / response','Environment state']],
      task:['FIRST SUCCESS','Make the first working request the core task.','Examples, errors and next steps should support a developer moving from trial to dependable integration.',['Try a request','Inspect the response','Handle an error']],
      steps:['Choose the relevant resource','Make a bounded request','Inspect the response and errors','Move to the supported integration path'],
      integrations:[['API','Primary programmable surface.'],['Webhooks','Event delivery where the capability needs it.'],['Identity','Keys and access remain explicit.'],['Data','Schemas and retention stay documented.']],
      proof:[['01','Interface visible'],['02','Errors explained'],['03','Docs connected']],
      final:['NEXT REQUEST','Move from reading to a working integration.','Explore the API','Read the docs']
    },
    workspace:{
      hero:['WORK / OUTCOME','Move the core work from queue to verified outcome.','A task-first application story with ownership, workflow state and proof arranged around the work users repeat.','Open the workflow','See how it works'],
      navigation:['Workspace','Workflow','Team','Integrations','Security','Plans'],
      product:['WORK SURFACE','Make the real work visible before the feature inventory.','The product should explain the objects, ownership and state users actually manipulate.',['Work queue','Current state','Ownership']],
      task:['NEXT ACTION','Show what needs attention now.','A useful task surface makes the next decision and its consequences obvious.',['Priority work','Context','Verified outcome']],
      steps:['Connect the required context','Resolve the next action','Hand off with clear ownership','Verify the outcome'],
      integrations:[['Data','Bring in only required context.'],['Identity','Keep users and authority explicit.'],['Automation','Automate bounded repetitive steps.'],['Analytics','Measure the workflow after it is legible.']],
      proof:[['01','Work visible'],['02','Ownership clear'],['03','Outcome traceable']],
      final:['NEXT WORKFLOW','Start with the work users actually need to finish.','Open the workflow','Review integrations']
    }
  };
  const m=modes[mode], itemize=xs=>xs.map(title=>({title,body:'Shown as product context; live values require an approved product or connector source.'}));
  return {
    hero:{eyebrow:m.hero[0],headline:m.hero[1],subheadline:m.hero[2],primary:m.hero[3],secondary:m.hero[4]},
    navigation:m.navigation,
    'product-proof':{kicker:m.product[0],title:m.product[1],body:m.product[2],items:itemize(m.product[3])},
    'task-preview':{kicker:m.task[0],title:m.task[1],body:m.task[2],items:itemize(m.task[3])},
    'feature-grid':{kicker:'CAPABILITIES',title:'Capabilities follow the primary task.',items:['Observe','Decide','Act','Verify'].map((title,i)=>({title,body:['Expose the state needed for the decision.','Keep the next decision legible.','Make the permitted action explicit.','Show the resulting state and evidence.'][i]}))},
    workflow:{kicker:'WORKFLOW',title:'The product journey follows the work.',steps:m.steps},
    integrations:{kicker:'INTEGRATIONS',title:'Connect systems only where the workflow needs them.',items:m.integrations.map(([title,body])=>({title,body}))},
    'latest-content':{kicker:'DOCUMENTATION',title:'Keep reference material next to the workflow.',items:(docs?['Quickstart','Reference','Operational guide']:['Product guide','Workflow guide','Change notes']).map((title,i)=>({title,meta:docs?'DOCS':'GUIDE',body:'Documentation content requires an approved product source.',mediaLabel:`Guide ${pad(i+1)}`}))},
    proof:{kicker:'OPERATIONAL PROOF',metrics:m.proof},
    security:{kicker:'SECURITY / CONTROL',metrics:[['01','Authority explicit'],['02','Sensitive actions bounded'],['03','Evidence retained']]},
    pricing:{kicker:'PLANS',title:'Commercial facts stay source-backed.',items:['Start','Team','Scale'].map(title=>({title,price:'Plan data required',body:'Price and entitlement require an approved commercial source.'}))},
    faq:{kicker:'PRODUCT QUESTIONS',items:[['What is the primary task?',m.task[1]],['What data is live?','Only data from an approved connector or product source is treated as live.'],['How are risky actions handled?','Authority, validation and resulting state stay explicit.']]},
    final:{eyebrow:m.final[0],headline:m.final[1],primary:m.final[2],secondary:m.final[3]},
    footer:{location:'Product workspace',newsletter:'Product, workflow and operational updates.'}
  };
}

function digitalExperience(plan){
  const text=String(plan.project.brief||'').toLowerCase(), artists=/(artist|artists|umělc|umelec)/i.test(text), installations=/(installation|installations|exhibit|exhibition|výstav|vystav)/i.test(text), story=/(story|narrative|chapter|příběh|pribeh)/i.test(text);
  return {
    hero:{eyebrow:'ENTER / EXPLORE',headline:'Move through the exhibition as a living sequence.',subheadline:`${story?'Story, ':''}${installations?'installations, ':''}${artists?'artist context and ':''}visual layers arranged for exploration rather than a portfolio index.`,primary:'Enter the experience',secondary:'Explore the works'},
    navigation:['Experience','Installations','Artists','Archive','About'],
    experience:{kicker:'EXPERIENCE',title:'Move through story, space and artifact.',body:'The interface behaves like part of the exhibition: sequence first, context when it helps, navigation always recoverable.',features:[['NARRATIVE PATH','Progress through scenes or chapters without losing orientation.'],['INSTALLATION VIEW','Give spatial work enough room to read as an environment.'],['ARTIST CONTEXT','Attach authorship and context without breaking the visual rhythm.'],['EVOLVING LAYER','Support changing works or states without pretending provisional content is final.']]},
    gallery:{kicker:'SCENES / WORKS',title:'A visual sequence with changing scale.',items:['Opening scene','Installation view','Artifact detail','Artist perspective','Transition','Afterimage'].map((title,i)=>({title,body:'Curatorial caption requires an approved exhibition source.',mediaLabel:`Exhibition ${pad(i+1)}`}))},
    featured:{kicker:'WORKS / CHAPTERS',title:'Surface the pieces that move the experience forward.',items:['Installation','Artist work','Story chapter','Evolving layer'].map((title,i)=>({title,body:'Title, authorship and curatorial context require approved source material.',mediaLabel:`Work ${pad(i+1)}`}))},
    statement:{kicker:'CURATORIAL IDEA',quote:'The interface should feel like part of the exhibition, not a catalogue wrapped around it.'},
    about:{kicker:'CONTEXT',title:'Curatorial context without stopping the experience.',body:'Purpose, contributors and production context belong close to the work while remaining clearly secondary to exploration.'},
    faq:{kicker:'VISITOR GUIDE',items:[['How do I move through it?','Follow the sequence or jump between works without losing your place.'],['What is source-backed?','Artwork titles, artists and curatorial facts require approved exhibition content.'],['Can the exhibition change?','The structure supports evolving scenes while keeping provenance explicit.']]},
    final:{eyebrow:'CONTINUE / RETURN',headline:'Keep exploring the work at your own pace.',primary:'Enter the experience',secondary:'View the archive'},
    footer:{location:'Digital exhibition',newsletter:'Exhibition updates and new works.'}
  };
}

function portfolio(plan){return {hero:{eyebrow:'SELECTED / WORK',headline:'The work should make the introduction.',subheadline:'A deliberate edit of projects, process and point of view.',primary:'View selected work',secondary:'Start a project'},navigation:['Work','Case studies','About','Journal','Contact'],'selected-work':{kicker:'SELECTED WORK',items:Array.from({length:4},(_,i)=>({title:['Signal House','Afterimage','Material Study','Public System'][i],meta:['Identity','Digital','Campaign','Experience'][i],mediaLabel:`Project ${pad(i+1)}`}))},gallery:{kicker:'ARCHIVE',title:'A wider visual rhythm.',items:Array.from({length:6},(_,i)=>({title:`Frame ${pad(i+1)}`,mediaLabel:`Archive ${pad(i+1)}`}))},'case-study':{kicker:'CASE STUDY',title:'Show the thinking behind the outcome.',body:'Context, decision, craft and result should read as one narrative.'},statement:{kicker:'POINT OF VIEW',quote:'Good design makes the decision easier before it makes the surface prettier.'},about:{kicker:'ABOUT',title:'Enough context to make the work human.',body:'Practice, point of view and the right amount of biography.'},final:{eyebrow:'START A PROJECT',headline:'Make the next thing worth showing.',primary:'Start a project',secondary:'Email'},footer:{location:'Independent practice',newsletter:'New work and occasional notes.'}}}


function editorial(plan){
  const brand=plan.brand.identity.name;
  return {hero:{eyebrow:'LATEST / PERSPECTIVE',headline:'Stories worth returning to.',subheadline:`A focused publication from ${brand}, organised for reading, discovery and return visits.`,primary:'Read latest',secondary:'Browse topics'},navigation:['Latest','Topics','Authors','Issues','Newsletter'],'latest-content':{kicker:'LATEST',title:'Current stories and analysis.',items:['Lead story','Analysis','Interview','Field note'].map((title,i)=>({title,meta:['FEATURE','ANALYSIS','INTERVIEW','NOTE'][i],body:'Editorial content remains provisional until an approved source is bound.',mediaLabel:`Story ${pad(i+1)}`}))},categories:{kicker:'TOPICS',title:'Browse by subject.',items:['Latest','Analysis','Culture','Ideas'].map(title=>({title,body:'A stable editorial topic, not an internal implementation category.'}))},newsletter:{kicker:'NEWSLETTER',title:'A direct line to new work.',body:'Subscription copy stays explicit about what readers receive.',cta:'Subscribe'},proof:{kicker:'EDITORIAL STANDARD',metrics:[['01','Clear authorship'],['02','Source-aware publishing'],['03','Readable hierarchy']]},final:{eyebrow:'KEEP READING',headline:'Return for the next useful story.',primary:'Browse latest',secondary:'Subscribe'},footer:{location:'Independent publication',newsletter:'New stories and editorial releases.'}};
}

function hospitality(plan){
  const loc=plan.brand.content.location||'the destination';
  return {hero:{eyebrow:'STAY / EXPERIENCE',headline:'Stay for the place, book with confidence.',subheadline:`Rooms, atmosphere and useful local context in ${loc}, with the booking path kept clear.`,primary:'Check availability',secondary:'Explore the stay'},navigation:['Rooms','Experience','Gallery','Location','Book'],services:{kicker:'THE STAY',title:'Choose the right way to stay.',items:['Rooms','Experience','Hospitality','Local context'].map((title,i)=>({title,body:['Compare the stay options without hunting for basics.','Show what makes the place worth choosing.','Make service expectations clear before arrival.','Connect the property to the destination.'][i]}))},gallery:{kicker:'THE PLACE',title:'See the atmosphere before booking.',items:Array.from({length:6},(_,i)=>({title:['Rooms','Common spaces','Details','Experience','Location','After dark'][i],mediaLabel:`Stay ${pad(i+1)}`}))},booking:{kicker:'BOOK DIRECT',title:'Availability before unnecessary forms.',items:[{title:'Availability',price:'Live provider required',body:'Dates and rates remain provisional until a booking source is connected.'}]},availability:{kicker:'AVAILABILITY',title:'Choose dates with clear next steps.',items:[{title:'Stay options',price:'Live rate required',body:'No fabricated inventory or pricing.'}]},location:{kicker:'LOCATION',title:`Make ${loc} part of the decision.`,body:'Directions, nearby context and arrival information should support the stay.'},final:{eyebrow:'YOUR STAY',headline:'Check the dates that work.',primary:'Check availability',secondary:'Contact the property'},footer:{location:loc,newsletter:'Occasional stay and destination updates.'}};
}

function healthcare(plan){
  const loc=plan.brand.content.location||'your area';
  return {hero:{eyebrow:'CARE / CLARITY',headline:'Understand the next care step.',subheadline:'Clear service information, clinician context and a direct path to booking without unsupported outcome claims.',primary:'Book an appointment',secondary:'View services'},navigation:['Services','Clinicians','How it works','Location','Book'],services:{kicker:'SERVICES',title:'Start from the care you need.',items:['Consultation','Assessment','Ongoing care','Specialist support'].map(title=>({title,body:'Scope and suitability must be confirmed by the real provider.'}))},team:{kicker:'CLINICIANS',title:'Know who provides the care.',items:['Clinician','Specialist','Care team'].map((title,i)=>({title,meta:'Credentials require verified provider data',mediaLabel:`Clinician ${pad(i+1)}`}))},process:{kicker:'WHAT TO EXPECT',title:'A clear path before the visit.',steps:['Choose the relevant service','Confirm appointment details','Receive provider instructions']},proof:{kicker:'TRUST',metrics:[['01','Verified provider information'],['02','Clear accessibility details'],['03','No unsupported medical claims']]},booking:{kicker:'APPOINTMENTS',title:'Book the appropriate next step.',items:[{title:'Appointment',price:'Provider data required',body:'Availability is only shown when backed by a real scheduling source.'}]},location:{kicker:'VISIT',title:`Plan the visit in ${loc}.`,body:'Access, hours and directions should be verified before publication.'},final:{eyebrow:'NEXT STEP',headline:'Arrange the right appointment.',primary:'Book an appointment',secondary:'Contact the clinic'},footer:{location:loc,newsletter:'Service updates and practical information.'}};
}

function company(plan){return {hero:{eyebrow:'CLARITY / PROOF',headline:'Make the value clear before the pitch.',subheadline:'A credible company presence built around outcomes, expertise and evidence.',primary:'Start a conversation',secondary:'See capabilities'},navigation:['Capabilities','Outcomes','Process','Team','Contact'],services:{kicker:'CAPABILITIES',items:['Strategy','Design','Delivery','Support'].map((title,i)=>({title,body:['Define the right problem.','Turn decisions into a coherent system.','Ship with accountable ownership.','Keep the result healthy after launch.'][i]}))},outcomes:{kicker:'OUTCOMES',metrics:[['01','Clearer decisions'],['02','Lower friction'],['03','Visible evidence']]},proof:{kicker:'PROOF',items:['Case evidence','Client signal','Operational proof'].map(title=>({title,body:'Evidence belongs close to the claim it supports.'}))},process:{kicker:'PROCESS',steps:['Understand','Resolve','Deliver']},team:{kicker:'TEAM',items:['Lead','Design','Engineering'].map((title,i)=>({title,meta:'Accountable owner',mediaLabel:`Team ${pad(i+1)}`}))},faq:{kicker:'FAQ',items:[['How do we start?','With the decision that matters most.'],['How is scope controlled?','Explicit deliverables and change boundaries.'],['Who owns the output?','Ownership is made clear before delivery.']]},final:{eyebrow:'NEXT',headline:'Start the conversation.',primary:'Contact us',secondary:'See work'},footer:{location:'Independent team',newsletter:'Useful releases and field notes.'}}}



function commerce(plan){
  return {hero:{eyebrow:'SHOP / DISCOVER',headline:'Find the right product without the maze.',subheadline:'Clear categories, product context, comparison and trust signals before checkout.',primary:'Browse products',secondary:'Explore categories'},navigation:['Shop','Categories','Featured','Reviews','Help'],categories:{kicker:'CATEGORIES',title:'Start from what you need.',items:['Essentials','Featured','Specialist','New'].map(title=>({title,body:'A customer-facing category placeholder until real catalog data is connected.'}))},featured:{kicker:'FEATURED',title:'Useful products, surfaced early.',items:['Featured product','Popular choice','New arrival','Specialist option'].map((title,i)=>({title,body:'Product copy and availability require an approved catalog source.',mediaLabel:`Product ${pad(i+1)}`}))},comparison:{kicker:'COMPARE',title:'Make the differences legible.',items:['Use case','Fit','Details','Support'].map(title=>({title,body:'Comparison criteria should come from verified product data.'}))},testimonials:{kicker:'REVIEWS',title:'Proof without invented praise.',items:['Verified review source','Customer evidence','Product feedback'].map(title=>({title,body:'No testimonial is fabricated; bind a verified review source before publication.'}))},pricing:{kicker:'BUYING OPTIONS',title:'Price only when the catalog knows it.',items:[{title:'Product option',price:'Live price required',body:'Pricing and stock remain provisional until commerce data is connected.'}]},final:{eyebrow:'READY TO CHOOSE',headline:'Continue with the product that fits.',primary:'Browse products',secondary:'Get help'},footer:{location:'Online store',newsletter:'Product releases and useful updates.'}};
}

function nonprofit(plan){
  return {hero:{eyebrow:'IMPACT / ACTION',headline:'Show the work, then invite action.',subheadline:'Impact, research and campaigns should be understandable before asking for support.',primary:'See the impact',secondary:'Get involved'},navigation:['Impact','Research','Campaigns','Get involved','Donate'],outcomes:{kicker:'IMPACT',title:'Evidence belongs next to the mission.',metrics:[['01','Verified impact data required'],['02','Source-backed research'],['03','Transparent use of support']]},proof:{kicker:'EVIDENCE',title:'Make claims reviewable.',items:['Impact reporting','Research sources','Programme evidence'].map(title=>({title,body:'Publish only evidence backed by approved organisational data.'}))},'latest-content':{kicker:'UPDATES',title:'Current work and field notes.',items:['Campaign update','Research note','Community story'].map((title,i)=>({title,meta:'UPDATE',body:'Provisional story slot pending approved content.',mediaLabel:`Impact ${pad(i+1)}`}))},services:{kicker:'GET INVOLVED',title:'Different ways to contribute.',items:['Volunteer','Campaign','Partner','Support'].map(title=>({title,body:'Action details must be confirmed by the organisation.'}))},pricing:{kicker:'SUPPORT',title:'Contribution options without invented amounts.',items:[{title:'Donate',price:'Provider-defined',body:'Amounts and payment flow require the approved donation provider.'}]},final:{eyebrow:'TAKE PART',headline:'Choose the action that matches your intent.',primary:'Get involved',secondary:'See the impact'},footer:{location:'Impact organisation',newsletter:'Campaign, research and impact updates.'}};
}

function realEstate(plan){
  const loc=plan.brand.content.location||'the market';
  return {hero:{eyebrow:'PROPERTY / PLACE',headline:'Find a property by fit, not just a photo.',subheadline:`Listings, neighbourhood context and viewing steps for ${loc}, without fabricated inventory.`,primary:'Browse properties',secondary:'Explore neighbourhoods'},navigation:['Properties','Neighbourhoods','Agents','Viewings','Contact'],categories:{kicker:'PROPERTY TYPES',title:'Start with the kind of place.',items:['Homes','Apartments','New listings','Selected'].map(title=>({title,body:'Category structure is ready for a verified listings source.'}))},featured:{kicker:'FEATURED PROPERTIES',title:'Surface the right listings first.',items:['Selected property','New listing','Location highlight'].map((title,i)=>({title,body:'Address, price and availability require live listing data.',mediaLabel:`Property ${pad(i+1)}`}))},'latest-content':{kicker:'NEIGHBOURHOODS',title:'Understand the place around the property.',items:['Area guide','Local context','Market note'].map((title,i)=>({title,meta:'GUIDE',body:'Local content stays provisional until reviewed.',mediaLabel:`Area ${pad(i+1)}`}))},team:{kicker:'AGENTS',title:'Know who handles the viewing.',items:['Agent','Property specialist','Viewing contact'].map((title,i)=>({title,meta:'Verified profile required',mediaLabel:`Agent ${pad(i+1)}`}))},booking:{kicker:'VIEWINGS',title:'Request a viewing with clear next steps.',items:[{title:'Viewing request',price:'Schedule required',body:'Availability must come from the real agency workflow.'}]},location:{kicker:'LOCATION',title:`Explore ${loc} with context.`,body:'Map and neighbourhood information should come from verified location data.'},final:{eyebrow:'NEXT PROPERTY',headline:'Move from browsing to a real viewing.',primary:'Request a viewing',secondary:'Contact an agent'},footer:{location:loc,newsletter:'New listings and neighbourhood updates.'}};
}


function education(plan){
  return {hero:{eyebrow:'STUDY / DISCOVER',headline:'Find the programme, then understand the path in.',subheadline:'Programmes, admissions, campus life and evidence of teaching and research without burying the decision in institutional structure.',primary:'Explore programmes',secondary:'Admissions'},navigation:['Programmes','Admissions','Campus','Research','Student Life','Resources'],categories:{kicker:'PROGRAMMES',title:'Start with what you want to study.',items:['Undergraduate','Postgraduate','Professional','Research'].map(title=>({title,body:'Programme facts, entry requirements and dates require approved academic data.'}))},featured:{kicker:'WHY STUDY HERE',title:'Show the academic experience, not slogans.',items:['Teaching','Research','Campus','Student support'].map((title,i)=>({title,body:'Evidence and claims must be backed by the institution.',mediaLabel:`Academic ${pad(i+1)}`}))},process:{kicker:'ADMISSIONS',title:'Make the application path legible.',steps:['Choose a programme','Check verified requirements','Apply through the approved admissions flow']},gallery:{kicker:'CAMPUS',title:'See the learning environment.',items:Array.from({length:5},(_,i)=>({title:['Learning spaces','Campus life','Libraries','Studios','Community'][i],mediaLabel:`Campus ${pad(i+1)}`}))},'latest-content':{kicker:'RESEARCH / NEWS',title:'Current academic work.',items:['Research story','Faculty insight','Student update'].map((title,i)=>({title,body:'Publication content remains provisional until approved.',mediaLabel:`Academic story ${pad(i+1)}`}))},proof:{kicker:'ACADEMIC EVIDENCE',metrics:[['01','Accreditation source required'],['02','Verified programme data'],['03','Published admissions criteria']]},final:{eyebrow:'NEXT STEP',headline:'Choose the programme that fits.',primary:'Explore programmes',secondary:'View admissions'},footer:{location:'Campus information requires verified institutional data',newsletter:'Programme, research and admissions updates.'}};
}
function careers(plan){
  return {hero:{eyebrow:'JOBS / MATCH',headline:'Find the role by fit, not by noise.',subheadline:'Searchable opportunities, company context and useful career guidance with employer actions kept separate from candidate flow.',primary:'Browse jobs',secondary:'For employers'},navigation:['Jobs','Companies','Career Advice','For Employers'],categories:{kicker:'JOBS',title:'Search by the work that matters.',items:['Engineering','Product','Design','Operations'].map(title=>({title,body:'Live vacancy counts require an approved jobs source.'}))},featured:{kicker:'OPEN ROLES',title:'Surface relevant opportunities first.',items:['Featured role','New opening','Specialist role','Remote option'].map((title,i)=>({title,body:'Role, salary and availability must come from verified vacancy data.',mediaLabel:`Role ${pad(i+1)}`}))},team:{kicker:'COMPANIES',title:'Give candidates enough employer context.',items:['Employer profile','Team profile','Hiring company'].map((title,i)=>({title,meta:'Verified employer profile required',mediaLabel:`Company ${pad(i+1)}`}))},'latest-content':{kicker:'CAREER ADVICE',title:'Useful context before the application.',items:['Interview guide','Salary guide','Career path'].map((title,i)=>({title,body:'Guidance is editorial content, never fabricated market data.',mediaLabel:`Advice ${pad(i+1)}`}))},services:{kicker:'FOR EMPLOYERS',title:'A separate hiring path.',items:['Post a role','Employer profile','Hiring support'].map(title=>({title,body:'Commercial terms require the real recruiting provider.'}))},final:{eyebrow:'NEXT ROLE',headline:'Move from search to a real opportunity.',primary:'Browse jobs',secondary:'For employers'},footer:{location:'Job availability requires live vacancy data',newsletter:'New roles and useful career updates.'}};
}
function industrial(plan){
  return {hero:{eyebrow:'ENGINEERING / EVIDENCE',headline:'Lead with the system, specification and proof.',subheadline:'Products, capabilities, industries and case evidence arranged for technical evaluation before a request for quote.',primary:'Explore products',secondary:'Request a quote'},navigation:['Products','Capabilities','Industries','Case Studies','Support','Request Quote'],services:{kicker:'CAPABILITIES',title:'Show what the engineering system can do.',items:['Engineering','Integration','Manufacturing','Support'].map(title=>({title,body:'Capability claims require approved technical documentation.'}))},categories:{kicker:'INDUSTRIES',title:'Organise proof by operating context.',items:['Manufacturing','Logistics','Process','Infrastructure'].map(title=>({title,body:'Industry fit must be supported by real product and project evidence.'}))},featured:{kicker:'PRODUCTS',title:'Products with useful technical context.',items:['System','Module','Control','Service'].map((title,i)=>({title,body:'Specifications require a verified product source.',mediaLabel:`Product ${pad(i+1)}`}))},outcomes:{kicker:'ENGINEERING PROOF',metrics:[['01','Verified specification'],['02','Traceable project evidence'],['03','Documented support scope']]},'case-study':{kicker:'CASE STUDY',title:'Show the operating problem, solution and verified result.',body:'Performance, savings and uptime claims must be source-backed.'},process:{kicker:'REQUEST FOR QUOTE',title:'Turn requirements into a bounded engineering enquiry.',steps:['Describe the application','Confirm technical requirements','Receive a scoped response']},faq:{kicker:'TECHNICAL SUPPORT',items:[['Where are specifications?','Bind approved technical documentation.'],['What certifications apply?','Publish only verified certification data.'],['How is support handled?','Support scope must come from the actual service model.']]},final:{eyebrow:'ENGINEERING ENQUIRY',headline:'Start with the application requirements.',primary:'Request a quote',secondary:'Technical support'},footer:{location:'Industrial supplier',newsletter:'Product, engineering and support updates.'}};
}
function financeContent(plan){
  return {hero:{eyebrow:'ADVICE / TRUST',headline:'Make the financial decision understandable before the consultation.',subheadline:'Services, planning approach, security and regulated documents presented without performance promises or invented returns.',primary:'Book a consultation',secondary:'Explore services'},navigation:['Services','Planning','Insights','Security','Documents','Consultation'],services:{kicker:'SERVICES',title:'Start from the financial need.',items:['Planning','Investing','Retirement','Business advice'].map(title=>({title,body:'Service scope and suitability require approved firm information.'}))},process:{kicker:'PLANNING',title:'A clear advisory path.',steps:['Understand objectives','Review verified options and constraints','Agree the next documented step']},'latest-content':{kicker:'INSIGHTS',title:'Context, not promises.',items:['Market note','Planning guide','Regulatory update'].map((title,i)=>({title,body:'No performance forecast is fabricated; editorial content requires review.',mediaLabel:`Insight ${pad(i+1)}`}))},security:{kicker:'SECURITY',title:'Make controls and custody clear.',metrics:[['01','Verified regulatory status'],['02','Documented security controls'],['03','Explicit data handling']]},proof:{kicker:'TRUST',metrics:[['01','Credentials require source'],['02','Fees require approved disclosure'],['03','No unsupported return claims']]},booking:{kicker:'CONSULTATION',title:'Book a real conversation.',items:[{title:'Consultation',price:'Firm-defined',body:'Availability and fees require the approved scheduling source.'}]},final:{eyebrow:'NEXT STEP',headline:'Discuss the decision with verified context.',primary:'Book a consultation',secondary:'Read the documents'},footer:{location:'Financial services',newsletter:'Planning and regulatory updates.'}};
}
function community(plan){
  return {hero:{eyebrow:'MEMBERSHIP / PEOPLE',headline:'Make the value of belonging visible.',subheadline:'Benefits, people, events and resources arranged around joining and participating rather than a generic organisation brochure.',primary:'Explore membership',secondary:'View events'},navigation:['Membership','Events','Directory','Resources','Committees','Join'],services:{kicker:'MEMBERSHIP',title:'What membership enables.',items:['Network','Resources','Events','Representation'].map(title=>({title,body:'Benefit details require approved association content.'}))},'next-event':{kicker:'NEXT EVENT',title:'Member event',date:'Date required',time:'Time required',location:'Venue required',lineup:[],cta:'View events'},schedule:{kicker:'EVENTS',title:'A visible participation rhythm.',steps:['Discover an event','Check member access','Register through the approved flow']},team:{kicker:'DIRECTORY',title:'People and committees with clear roles.',items:['Member','Committee lead','Working group'].map((title,i)=>({title,meta:'Verified profile required',mediaLabel:`Member ${pad(i+1)}`}))},'latest-content':{kicker:'RESOURCES',title:'Useful material for members.',items:['Guidance','Industry update','Committee note'].map((title,i)=>({title,body:'Resource content remains provisional until approved.',mediaLabel:`Resource ${pad(i+1)}`}))},pricing:{kicker:'JOIN',title:'Membership terms without invented dues.',items:[{title:'Membership',price:'Approved dues required',body:'Eligibility and dues must come from the association.'}]},final:{eyebrow:'TAKE PART',headline:'Join the community with clear expectations.',primary:'Explore membership',secondary:'View events'},footer:{location:'Membership organisation',newsletter:'Events, resources and member updates.'}};
}
function restaurant(plan){
  const loc=plan.brand.content.location||'the city';
  return {hero:{eyebrow:'TABLE / EXPERIENCE',headline:'See the food, the room and the reason to reserve.',subheadline:`Menu, atmosphere, private dining and practical details for ${loc}, with reservations kept one clear action away.`,primary:'Reserve a table',secondary:'View the menu'},navigation:['Menu','Reservations','Private Dining','Our Story','Gallery','Location'],services:{kicker:'MENU',title:'Let the menu lead the decision.',items:['À la carte','Seasonal menu','Drinks','Dietary guidance'].map(title=>({title,body:'Dishes, allergens and prices require the approved restaurant menu.'}))},featured:{kicker:'FROM THE KITCHEN',title:'Signature dishes without invented menu facts.',items:['Seasonal plate','Chef selection','House favourite'].map((title,i)=>({title,body:'Bind real dish content before publication.',mediaLabel:`Dish ${pad(i+1)}`}))},gallery:{kicker:'THE ROOM',title:'Food and atmosphere in equal measure.',items:Array.from({length:6},(_,i)=>({title:['Dining room','Kitchen','Plate','Bar','Private dining','Evening'][i],mediaLabel:`Restaurant ${pad(i+1)}`}))},booking:{kicker:'RESERVATIONS',title:'Choose a real available table.',items:[{title:'Table reservation',price:'Live availability required',body:'Times and capacity require the approved reservation provider.'}]},experience:{kicker:'OUR STORY',title:'A concise point of view behind the restaurant.',body:'Chef, sourcing and hospitality claims must be approved by the restaurant.'},location:{kicker:'VISIT',title:`Plan the visit in ${loc}.`,body:'Opening hours, address and access require verified venue data.'},final:{eyebrow:'YOUR TABLE',headline:'Reserve when the time works.',primary:'Reserve a table',secondary:'View the menu'},footer:{location:loc,newsletter:'Menu, event and seasonal updates.'}};
}
function professional(plan){
  return {hero:{eyebrow:'EXPERTISE / JUDGEMENT',headline:'Lead with the matter, the expertise and the people accountable for it.',subheadline:'Practice areas, professionals, industry context and credentials arranged for a high-trust decision.',primary:'Discuss your matter',secondary:'View practice areas'},navigation:['Practice Areas','Professionals','Industries','Insights','Offices','Contact'],services:{kicker:'PRACTICE AREAS',title:'Start from the matter that needs resolving.',items:['Advisory','Transactions','Disputes','Specialist support'].map(title=>({title,body:'Scope and jurisdiction require approved firm information.'}))},team:{kicker:'PROFESSIONALS',title:'Make expertise attributable.',items:['Partner','Specialist','Advisor','Team lead'].map((title,i)=>({title,meta:'Verified profile and credentials required',mediaLabel:`Professional ${pad(i+1)}`}))},categories:{kicker:'INDUSTRIES',title:'Context matters to the advice.',items:['Technology','Financial services','Industry','Public sector'].map(title=>({title,body:'Industry credentials require source-backed firm evidence.'}))},'latest-content':{kicker:'INSIGHTS',title:'Useful thinking, clearly dated.',items:['Briefing','Case note','Regulatory update'].map((title,i)=>({title,body:'Legal or professional guidance requires approved authorship and review.',mediaLabel:`Insight ${pad(i+1)}`}))},proof:{kicker:'CREDENTIALS',metrics:[['01','Verified professional profiles'],['02','Source-backed credentials'],['03','No fabricated case outcomes']]},location:{kicker:'OFFICES',title:'Know where the team operates.',body:'Office addresses and jurisdictions require verified firm data.'},final:{eyebrow:'NEXT STEP',headline:'Discuss the matter with the right team.',primary:'Contact the firm',secondary:'View professionals'},footer:{location:'Professional practice',newsletter:'Insights and practice updates.'}};
}
function florist(plan){
  const cs=plan.project.locale?.language==='cs';
  const loc=plan.brand.content.location||null;
  if(cs)return {
    hero:{eyebrow:'KVĚTINY / PŘÍLEŽITOST',headline:'Květiny pro chvíle, na kterých záleží.',subheadline:'Sezónní kytice, osobní vazba a jednoduché doručení nebo vyzvednutí.',primary:'Vybrat kytici',secondary:'Kytice na přání'},
    navigation:['Kytice','Podle příležitosti','Svatby','Předplatné','Doručení'],
    categories:{kicker:'PODLE PŘÍLEŽITOSTI',title:'Začněte tím, komu a proč květiny dáváte.',items:[['Narozeniny','Radostná kytice podle nálady a sezóny.'],['Láska a výročí','Výrazná nebo jemná vazba pro osobní okamžik.'],['Poděkování','Květiny jako jednoduché a osobní gesto.'],['Rozloučení','Citlivá floristika s důrazem na tón a přání.']].map(([title,body])=>({title,body}))},
    featured:{kicker:'SEZÓNNÍ KYTICE',title:'Každá vazba začíná tím, co právě kvete.',items:[['Luční','Vzdušná, přirozená a nepravidelná vazba.'],['Jemná','Světlá paleta a klidný romantický charakter.'],['Výrazná','Sytější kontrast a silnější silueta.'],['Zelená a bílá','Čistá botanická kombinace s texturou listů.']].map(([title,body],i)=>({title,body,mediaLabel:`Kytice ${pad(i+1)}`}))},
    services:{kicker:'FLORISTICKÉ SLUŽBY',title:'Nejen hotová kytice.',items:[['Kytice na přání','Řekněte příležitost, náladu a barevný směr.'],['Svatby a události','Květinový koncept od osobních květin po výzdobu prostoru.'],['Květinové předplatné','Pravidelná floristika pro domov, kancelář nebo provoz.'],['Doručení a vyzvednutí','Oblast, datum a způsob převzetí se potvrzují při objednávce.']].map(([title,body])=>({title,body}))},
    gallery:{kicker:'Z FLORISTICKÉHO STOLU',title:'Barva, textura, sezóna.',items:['Jarní vazba','Pivoňky a zeleň','Minimalistická bílá','Luční textura','Svatební detail','Květiny pro interiér'].map((title,i)=>({title,mediaLabel:`Floristika ${pad(i+1)}`}))},
    process:{kicker:'OD KVĚTIN K DORUČENÍ',title:'Tři jednoduché kroky.',steps:[{title:'Vyberte kytici nebo příležitost',body:'Začněte stylem, barvou nebo tím, komu jsou květiny určené.'},{title:'Přidejte přání a preference',body:'Doplňte vzkaz, velikost a případné floristické přání.'},{title:'Potvrďte doručení nebo vyzvednutí',body:'Termín a místo se potvrdí před dokončením objednávky.'}]},
    'latest-content':{kicker:'SEZÓNA / PÉČE',title:'Květiny žijí déle s dobrým kontextem.',items:['Co právě kvete','Jak prodloužit život kytice','Květiny podle příležitosti'].map((title,i)=>({title,meta:'FLORISTIKA',body:'Praktický floristický obsah pro výběr a péči.',mediaLabel:`Tip ${pad(i+1)}`}))},
    location:{kicker:'MÍSTNÍ KVĚTINÁŘSTVÍ',title:loc?`Najdete nás v ${loc}.`:'Osobní floristika blízko vás.',body:'Adresa, otevírací doba a oblast doručení patří na jedno místo.',cta:'Trasa a kontakt'},
    faq:{kicker:'ČASTÉ DOTAZY',items:[['Mohu vybrat konkrétní květiny?','Můžete uvést preference; finální vazba respektuje dostupnost a sezónu.'],['Lze přidat osobní vzkaz?','Ano, objednávka počítá s krátkým věnováním pro příjemce.'],['Jak funguje doručení?','Dostupný termín a oblast doručení se potvrdí před objednávkou.']]},
    final:{eyebrow:'PRO NĚKOHO / PRO RADOST',headline:'Vyberte květiny podle okamžiku.',primary:'Vybrat kytici',secondary:'Kytice na přání'},
    footer:{location:loc||'Místní květinářství',newsletter:'Sezónní květiny, péče a nové floristické kolekce.'}
  };
  return {
    hero:{eyebrow:'FLOWERS / OCCASION',headline:'Flowers for the moments that matter.',subheadline:'Seasonal bouquets, personal floristry and a simple path to delivery or pickup.',primary:'Shop bouquets',secondary:'Create a custom bouquet'},
    navigation:['Bouquets','By Occasion','Weddings','Subscriptions','Delivery'],
    categories:{kicker:'SHOP BY OCCASION',title:'Start with who the flowers are for.',items:[['Birthday','Bright, generous flowers shaped around the mood of the day.'],['Love & anniversary','Romantic arrangements from quiet to expressive.'],['Thank you','A personal floral gesture without unnecessary ceremony.'],['Sympathy','Thoughtful floristry with a calm, respectful tone.']].map(([title,body])=>({title,body}))},
    featured:{kicker:'SEASONAL BOUQUETS',title:'Built around what is beautiful now.',items:[['Meadow','Loose, natural composition with movement and texture.'],['Soft blush','A pale, romantic palette with an airy silhouette.'],['Wild garden','Layered seasonal flowers with stronger contrast.'],['White & green','Clean botanical structure with foliage and texture.']].map(([title,body],i)=>({title,body,mediaLabel:`Bouquet ${pad(i+1)}`}))},
    services:{kicker:'FLORIST SERVICES',title:'More than an off-the-shelf bouquet.',items:[['Custom bouquets','Share the occasion, mood and colour direction.'],['Weddings & events','A floral direction from personal flowers to venue arrangements.'],['Flower subscriptions','Regular floristry for homes, offices and hospitality spaces.'],['Delivery & pickup','Area, date and handover method are confirmed during ordering.']].map(([title,body])=>({title,body}))},
    gallery:{kicker:'FROM THE FLOWER TABLE',title:'Colour, texture, season.',items:['Spring stems','Peonies & foliage','Minimal white','Meadow texture','Wedding detail','Flowers for interiors'].map((title,i)=>({title,mediaLabel:`Floristry ${pad(i+1)}`}))},
    process:{kicker:'FROM FLOWERS TO THEIR DOOR',title:'Three clear steps.',steps:[{title:'Choose a bouquet or occasion',body:'Start with style, colour or the person you are buying for.'},{title:'Add a note and preferences',body:'Include a message, size direction and any florist notes.'},{title:'Confirm delivery or pickup',body:'Date and destination are confirmed before the order is completed.'}]},
    'latest-content':{kicker:'SEASON / CARE',title:'Flowers last longer with good context.',items:['What is in season','How to care for a bouquet','Flowers by occasion'].map((title,i)=>({title,meta:'FLORISTRY',body:'Useful guidance for choosing and caring for flowers.',mediaLabel:`Guide ${pad(i+1)}`}))},
    location:{kicker:'LOCAL FLORIST',title:loc?`Find us in ${loc}.`:'Personal floristry, close to home.',body:'Address, opening hours and delivery area belong in one clear place.',cta:'Directions & contact'},
    faq:{kicker:'FLOWER QUESTIONS',items:[['Can I request specific flowers?','You can share preferences; the final arrangement follows season and availability.'],['Can I add a personal note?','Yes. The order flow includes a short message for the recipient.'],['How does delivery work?','Available dates and delivery areas are confirmed before ordering.']]},
    final:{eyebrow:'FOR SOMEONE / FOR JOY',headline:'Choose flowers for the moment.',primary:'Shop bouquets',secondary:'Create a custom bouquet'},
    footer:{location:loc||'Local florist',newsletter:'Seasonal flowers, care notes and new arrangements.'}
  };
}

function richCommerce(plan){
  return {hero:{eyebrow:'SHOP / CHOOSE',headline:'Find the right product by need, compare by fit, buy from verified product data.',subheadline:'Collections, filters, product context, reviews, delivery and support arranged around a real buying decision.',primary:'Shop products',secondary:'Explore collections'},navigation:['Shop','Categories','Featured','Compare','Reviews','Help'],categories:{kicker:'COLLECTIONS',title:'Start from what you need.',items:['Core collection','New','Specialist','Seasonal'].map(title=>({title,body:'Collection membership requires the approved catalog.'}))},featured:{kicker:'FEATURED PRODUCTS',title:'Merchandise with context, not generic cards.',items:['Featured product','Popular choice','New arrival','Specialist option'].map((title,i)=>({title,body:'Product copy, stock and price require an approved commerce source.',mediaLabel:`Catalog ${pad(i+1)}`}))},comparison:{kicker:'COMPARE',title:'Compare the attributes that change the decision.',items:['Use case','Specification','Fit','Support'].map(title=>({title,body:'Comparison values require verified product attributes.'}))},testimonials:{kicker:'REVIEWS',title:'Use real customer evidence.',items:['Verified review','Customer evidence','Product feedback'].map(title=>({title,body:'No review text or rating is fabricated.'}))},'trust-safety':{kicker:'DELIVERY / RETURNS',title:'Make fulfilment rules visible.',metrics:[['01','Live shipping terms required'],['02','Approved returns policy'],['03','Verified payment provider']]},pricing:{kicker:'PRICE / STOCK',title:'Commercial facts come from the catalog.',items:[{title:'Product',price:'Live price required',body:'Price, discount and stock are never inferred.'}]},faq:{kicker:'HELP',items:[['Delivery?','Use the approved shipping policy.'],['Returns?','Use the approved returns policy.'],['Availability?','Use live stock data where supported.']]},final:{eyebrow:'READY TO BUY',headline:'Continue with the product that fits.',primary:'Shop products',secondary:'Get help'},footer:{location:'Online store',newsletter:'Product releases and useful updates.'}};
}

function corporateContent(plan){return {hero:{eyebrow:'POSITION / PROOF',headline:'Make the point of view visible before the capability list.',subheadline:'A corporate or agency presence organised around expertise, selected work, approach and accountable people rather than product UI.',primary:'See capabilities',secondary:'View work'},navigation:['Capabilities','Work','Approach','Team','Insights','Contact'],services:{kicker:'CAPABILITIES',title:'Expertise as a clear set of decisions.',items:['Strategy','Design','Delivery','Partnership'].map(title=>({title,body:'Capability detail should be tied to real services and evidence.'}))},'selected-work':{kicker:'SELECTED WORK',title:'Proof through representative work.',items:['Case study','Programme','Transformation','Launch'].map((title,i)=>({title,body:'Case evidence requires approved client or project data.',mediaLabel:`Work ${pad(i+1)}`}))},process:{kicker:'APPROACH',title:'Show how the work moves.',steps:['Frame the decision','Build the right system','Deliver and evidence the outcome']},team:{kicker:'PEOPLE',title:'Put accountable people near the work.',items:['Lead','Strategy','Design','Delivery'].map((title,i)=>({title,meta:'Verified profile required',mediaLabel:`Team ${pad(i+1)}`}))},'latest-content':{kicker:'INSIGHTS',title:'Current thinking without filler.',items:['Field note','Case reflection','Industry perspective'].map((title,i)=>({title,body:'Editorial content requires approval.',mediaLabel:`Insight ${pad(i+1)}`}))},final:{eyebrow:'NEXT PROJECT',headline:'Start with the decision that matters.',primary:'Start a conversation',secondary:'View work'},footer:{location:'Independent organisation',newsletter:'Work, releases and field notes.'}}}

function fallbackSection(id,plan){
  const title=id.replaceAll('-',' ').replace(/\b\w/g,m=>m.toUpperCase());
  if(['how-it-works','workflow','process','schedule'].includes(id)) return {kicker:title.toUpperCase(),title,steps:['Understand the need','Choose the right path','Complete the next action']};
  if(['proof','outcomes','security','trust-safety','trust-strip','logo-cloud'].includes(id)) return {kicker:title.toUpperCase(),title,metrics:[['01','Clear signal'],['02','Visible evidence'],['03','Lower uncertainty']]};
  if(['faq'].includes(id)) return {kicker:'FAQ',items:[['What happens next?','The next action stays visible and specific.'],['What is required?','Only the information needed for this step.'],['How is quality controlled?','The page is verified before release.']]};
  if(['statement','about','case-study','problem-solution','product-proof','task-preview'].includes(id)) return {kicker:title.toUpperCase(),title,body:'A focused section bound to the page goal, content model and visitor journey.'};
  if(['pricing','availability','booking'].includes(id)) return {kicker:title.toUpperCase(),title,items:[{title:'Standard',price:'From scope',body:'A clear commercial next step.'},{title:'Priority',price:'Custom',body:'For higher urgency or complexity.'}]};
  if(['featured','categories','search-results','comparison','testimonials','newsletter','supply-demand','feature-grid','services','integrations','latest-content'].includes(id)) return {kicker:title.toUpperCase(),title,items:['Primary','Secondary','Tertiary','Extended'].map((x,i)=>({title:x,body:'Purpose-built content slot '+(i+1)+'.'}))};
  if(id==='domain-signature') return {kicker:'DOMAIN SIGNATURE',title:'A composition synthesized for this specific idea.',body:'This section exists because no registry family was a sufficient semantic match.',items:[{title:'Intent',body:'Derived from the novel-domain model.'},{title:'Entities',body:'Mapped from the product ontology.'},{title:'Journey',body:'Composed from the primary user jobs.'}]};
  return {kicker:title.toUpperCase(),title,items:[{title:'Focus',body:'A purposeful section resolved by WEBFORGE.'}]};
}

function universal(plan){
  const brand=plan.brand.content, entities=(plan.product?.entities||[]).map(x=>x.name), jobs=plan.product?.userJobs||[], synth=plan.domain?.synthesis, domain=synth?.subject||plan.domain?.primary?.label||'Web product';
  const model={
    hero:{eyebrow:brand.eyebrow,headline:brand.headline,subheadline:brand.subheadline,primary:brand.primaryCta,secondary:brand.secondaryCta},
    navigation:(plan.siteBlueprint?.navigation||plan.experience?.navigation||[]).map(x=>typeof x==='string'?x:(x.label||x.id)).slice(0,7),
    final:{eyebrow:'NEXT STEP',headline:brand.primaryCta||'Take the next step.',primary:brand.primaryCta||'Continue',secondary:brand.secondaryCta||'Learn more'},
    footer:{location:brand.location||domain,newsletter:'Updates tied to this product, not generic filler.'}
  };
  const topicItems=(synth?.topics||[]).slice(0,4).map((x,i)=>({title:x.label,body:x.description,mediaLabel:`${x.label} ${pad(i+1)}`}));
  const entityItems=entities.slice(0,4).map((name,i)=>({title:name,body:`${name} is part of the ${domain} model described in the brief.`,mediaLabel:`${name} ${pad(i+1)}`}));
  const jobItems=jobs.slice(0,4).map((j,i)=>({title:j.goal,body:j.needs.join(' · '),mediaLabel:`Journey ${pad(i+1)}`}));
  const semanticItems=topicItems.length?topicItems:(entityItems.length?entityItems:jobItems);
  for(const id of plan.layout.sections){
    if(id==='hero'||id==='final-cta'||model[id])continue;
    const title=id.replaceAll('-',' ').replace(/\b\w/g,m=>m.toUpperCase());
    if(['categories','featured','search-results','comparison','testimonials','services','team','artists','gallery','feature-grid','latest-content','integrations'].includes(id)) model[id]={kicker:title.toUpperCase(),title:synth?.topics?.find(x=>x.sections?.includes(id))?.label||title,items:semanticItems};
    else if(['workflow','process','how-it-works','schedule'].includes(id)) model[id]={kicker:title.toUpperCase(),title,steps:jobs.slice(0,4).map(j=>j.goal)};
    else if(['proof','outcomes','security','trust-safety','trust-strip'].includes(id)) model[id]={kicker:title.toUpperCase(),title,metrics:[["01",semanticItems[0]?.title||domain],["02",semanticItems[1]?.title||jobs[0]?.goal||'Clear next step'],["03",jobs[0]?.goal||brand.primaryCta||'Useful action']]};
    else if(['pricing','availability','booking','next-event'].includes(id)) model[id]={kicker:title.toUpperCase(),title,items:[{title:'Primary action',price:'Resolved by connector',body:'Commercial data remains provisional until a real provider is bound.'}]};
    else if(id==='location') model[id]={kicker:'LOCATION',title:brand.location||'Location-aware experience',body:'Location data is shown only when a verified source is available.'};
    else if(id==='domain-signature') model[id]={kicker:synth?.direction?.id?.replaceAll('-',' ').toUpperCase()||'DOMAIN SIGNATURE',title:synth?.copy?.headline||domain,body:synth?.copy?.subheadline||'The page structure is derived from this brief rather than a fixed industry template.',items:semanticItems.slice(0,4)};
    else if(id==='statement') model[id]={kicker:'POINT OF VIEW',title:synth?.subject||domain,body:synth?.copy?.subheadline||brand.subheadline};
    else if(id==='experience') model[id]={kicker:'EXPERIENCE',title:synth?.copy?.headline||domain,body:synth?.copy?.subheadline||brand.subheadline,features:semanticItems.slice(0,4).map(x=>[x.title,x.body])};
    else if(id==='about') model[id]={kicker:'CONTEXT',title:`About ${synth?.subject||domain}`,body:synth?.copy?.subheadline||brand.subheadline};
    else if(id==='faq') model[id]={kicker:'FAQ',items:[['What can I do here?',jobs[0]?.goal||'Understand the offer and take the next useful action.'],['What data is real?','Production content must come from approved content or connector evidence.'],['What if a capability is missing?','WEBFORGE marks it UNRESOLVED rather than pretending it works.']]};
    else model[id]=fallbackSection(id,plan);
  }
  return model;
}

export function bindContent(plan){
  const a=plan.project.archetype;
  const useUniversal=plan.project.domain?.classification==='NOVEL'||(plan.project.domain?.classification==='HYBRID'&&plan.domain?.genome?.applicationDepth>=3);
  const d=plan.project.domainArchetype,profile=plan.designStrategy?.composition_profile?.siteArchetype;
  const brief=String(plan.project.brief||'').toLowerCase(),isRestaurant=d==='hospitality'&&/(restaurant|dining|chef|menu)/.test(brief)&&!/(hotel|resort|hostel|room|rooms|suite|suites)/.test(brief),isProfessional=d==='local-professional-service'&&/(law|legal|lawyer|attorney|accounting|accountant|consulting|consultant|advisory|firm)/.test(brief);
  const isCorporate=d==='generic-organization'&&/(agency|studio|corporate|company|consultancy)/.test(brief);
  const applicationProfile=['product-application','financial-application'].includes(profile);
  let model=applicationProfile?productApplication(plan):d==='digital-experience'?digitalExperience(plan):isCorporate?corporateContent(plan):useUniversal?universal(plan):d==='florist-retail'?florist(plan):d==='education-learning'?education(plan):d==='jobs-careers'?careers(plan):d==='industrial-b2b'?industrial(plan):d==='finance'?financeContent(plan):d==='community-membership'?community(plan):isRestaurant?restaurant(plan):isProfessional?professional(plan):d==='commerce-store'?richCommerce(plan):d==='editorial-publication'?editorial(plan):d==='hospitality'?hospitality(plan):d==='healthcare'?healthcare(plan):d==='nonprofit-impact'?nonprofit(plan):d==='real-estate'?realEstate(plan):a==='venue'?venue(plan):a==='local-service'?local(plan):['saas','web-app','marketplace'].includes(a)?product(plan):a==='portfolio'?portfolio(plan):company(plan);
  for(const id of plan.layout.sections) if(id!=='hero'&&id!=='final-cta'&&!model[id]) model[id]=fallbackSection(id,plan);
  model=localizeContentModel(plan,model);
  return {version:'webforge.content-binding.universal.v1',archetype:a,domainArchetype:plan.project.domainArchetype,brand:plan.brand.identity.name,locale:plan.project.locale?.tag||'en',model,source:{kind:'generated-seed',status:'PROVISIONAL',productionRequirement:'replace or approve generated seed content'}};
}
